spring.application.name=BACKEND

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?sslMode=REQUIRED&enabledTLSProtocols=TLSv1.2,TLSv1.3
spring.datasource.username=4B8taRbczG2SgfL.root
spring.datasource.password=LYFn6Rk8xm1eYqYM
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate/JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
